name: ayFLIX
options:
  bundleIdPrefix: com.ceresify
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""

targets:
  ayFLIX:
    type: application
    platform: iOS
    sources: [ayFLIX]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ayflix.ceresify.com
        PRODUCT_NAME: ayFLIX
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "NO"
    info:
      path: ayFLIX/Info.plist
      properties:
        CFBundleDisplayName: ayFLIX
        CFBundleName: ayFLIX
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: APPL
        CFBundleDevelopmentRegion: ar
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen:
          UIColorName: LaunchBackground
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        ITSAppUsesNonExemptEncryption: false
